name: Env-Demo-Workflow

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: staging

    steps:
      - name: Print environment variable
        run: |
          echo "Vari√°vel de ambiente DEPLOY_ENV: $DEPLOY_ENV"
        
