name: SecretDemo-Workflow

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variable
        run: |
          if [ -z "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY N√ÉO configurado!"
            exit 1
          else
            echo "API_KEY configurado"
          fi